### ISSUE TITLE
Another driver

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/win31-mouse-driver#2]
I just came across another driver here:
https://github.com/joncampbell123/doslib/tree/master/windrv

There are some notes about issues with the DDK sample driver that might be good to know of.

**Comment by stsp** [comment]
Have you tried it?
It seems to be using ps/2 API, not int33,
so I wonder if its interesting at all?

**Comment by jschwartzenberg** [comment]
No I didn't try it. It should also be able to use absolute movement with DOSBox-X pointer integration.

I thought maybe the "What Microsoft did wrong (or, the unnecessary methods used in their DDK sample driver)" bit in the README could be interesting.

**Comment by stsp** [comment]
I am not a windows programmer, and
this small win31 mouse driver is not the
right place for me to start learning. :)
It works, and this is all I need.
Not sure what is "DOSBox-X pointer integration" -
for me int33 driver works w/o any
"DOSBox-X pointer integration", and this is
all I need.

**Comment by jschwartzenberg** [comment]
Yep, makes sense. I also asked a bit here any the conclusion seems to be the same: https://github.com/joncampbell123/dosbox-x/issues/1003

**Comment by stsp** [comment]
You likely can't support scrolling normally
under win31. Perhaps the drivers you've
seen with scrolling, actually generate the
fake keyboard events.

**Comment by jschwartzenberg** [comment]
Yeah, I think they generate the window messages though a special hook.
