### ISSUE TITLE
This mouse driver is perhaps not so universal as advertised

### ISSUE THREAD

**Issue by Baron-von-Riedesel** [stsp/win31-mouse-driver#3]
A few days ago my old MS PS/2 mouse has ended its life.

So I'm currently restricted to use a USB wireless mouse. It works fine in DOS with CTMOUSE loaded. However, when I start Windows 3.1 in standard mode (CTMOUSE is NOT loaded then) the mouse behaves rather "erratic" - actually, it cannot be used. The keyboard still works, though.

I then remembered this driver - and since it's "universal" and based upon an Int 33h DOS driver, I thought it "should work".
Regrettably my experiments weren't successful: after activating this driver in system.ini, Win31 starts and shows the program manager screen, but then the system is "freezed", neither mouse nor keyboard can be used, actually, one has to press the reset button.

**Comment by stsp** [comment]
Try using it with hdpmi.
It wasn't tested with win386.exe.

**Comment by stsp** [comment]
Of course you still need ctmouse loaded.

**Comment by Baron-von-Riedesel** [comment]
> Try using it with hdpmi.

That was actually the first thing I did ( because the std. Win31 DOSX.EXE isn't happy with HimemX). There's no difference between hdpmi16 and dosx, system freezes with both extenders.

> Of course you still need ctmouse loaded.

Yes, I know that ( that "not loaded" in my initial post was when trying the standard Win31 mouse driver )
When ctmouse is NOT loaded and the "universal" driver is activated in system.ini, the system does NOT freeze, but there is also no mouse available, not even the mouse arrow pops up.

**Comment by stsp** [comment]
> no mouse available, not even the mouse arrow pops up.

This is very good because then
the detection works, which includes
a couple of int33 calls.
See https://github.com/dosemu2/win31-mouse-driver/blob/master/src/MOUSE.ASM#L746
(try_mouse_reset)

I updated build.sh script now for
the recent dosemu2 syntax, so you
need to run build.sh to build the driver.
It consists of 2 small asm files, full
of comments. I am sure you can find
the bug in 15 minutes. :)
I can't help with testing on a bare-metal
system, but it would be cool if you add
such support.

**Comment by Baron-von-Riedesel** [comment]
> I updated build.sh script now for the recent dosemu2 syntax, so you need to run build.sh to build the driver.

That's not needed, because I can build the driver in DOS - all tools needed are included in the zip

> It consists of 2 small asm files, full of comments. I am sure you can find the bug in 15 minutes. :)

Ok, I invested 15 minutes and noticed so far that it's indeed a pretty small thing. What makes it confusing is that very ugly cmacro.inc file...

Btw., the system doesn't "freeze" if I stay away from the mouse ( no move or button press ). If I were used to control Win31 with the keyboard only, I could probably find the problem within Windows.

**Comment by stsp** [comment]
Can it be that set user handler of int33
is not translated to realmode properly?

**Comment by stsp** [comment]
I mean, dosemu translates int33 and
dosx probably not?

**Comment by Baron-von-Riedesel** [comment]
> I mean, dosemu translates int33 and dosx probably not?

That's not unlikely. I changed the int 0x33, ax=0x0014 ( xchg event proc ) by 0x000C ( set event proc ) and then the freeze disappeared with hdpmi and the mouse worked in Win31 ( haven't tested dosx yet ).
However, hdpmi supports translation of int 0x33, ax=0x0014, at least it's implemented. Perhaps some regression...

**Comment by Baron-von-Riedesel** [comment]
Ok, mystery solved: It's the dosx extender only that has problems with int 0x33, function ax=0x0014. hdpmi16 works with both "universal" mouse driver versions, using int 0x33, ax=0x0014 or ax=0x000C.

In my tests yesterday with hdpmi16, I preloaded it and assumed it will be used automatically by Windows, but this is wrong. I forgot that I have to exchange DOSX.EXE in the system directory by that little stub (dosx.exe) provided by HX to force Windows to use hdpmi16.

**Comment by stsp** [comment]
Would you like to submit a patch please?
Btw its kinda silly that they dont support
a function used in their own sdk, so I am
still skeptical.

**Comment by Baron-von-Riedesel** [comment]
attached
[int33h.asm.TXT](https://github.com/dosemu2/win31-mouse-driver/files/8486772/int33h.asm.TXT)

**Comment by stsp** [comment]
Should now be fixed.
Indeed, there seem to be no
reliable way of translating 0x14.
dosemu takes the simple approach:
to return either prev PM handler or
NULL. Which means prev RM handler
can never be restored. And I think
that's a good impl.
What does hdpmi do?

**Comment by Baron-von-Riedesel** [comment]
> What does hdpmi do?

It does also not try to translate the real-mode addresses. They are stored in a table of "internal" real-mode callbacks. What the pm client supplies, is stored/returned internally by the host.

**Comment by stsp** [comment]
So it returns NULL on first call?

**Comment by Baron-von-Riedesel** [comment]
True.

**Comment by stsp** [comment]
Have you tested that things
now work as expected?

**Comment by Baron-von-Riedesel** [comment]
Everything works super-fantastically. :)

**Comment by stsp** [comment]
Thanks. :)
